### ISSUE TITLE
每次都备注文本，次数多了混在一起显得有点杂

### ISSUE THREAD

**Issue by pholaneckes** [LZH-sqrt2/lzhs_science_and_reallife_mod#1]
特别是要准备添加功能的备注，无论完成与否，只要没有替换原先所有的被备注的文件，备注都一直会在。是否有点凌乱？

**Comment by LZH-sqrt2** [comment]
指 SingleDirectionalLightShader？

**Comment by LZH-sqrt2** [comment]
虽然不好，但我不打算改以前的，以后会改成TODO，在debug_helper里没有一个注释（或许有些不好？）

**Comment by LZH-sqrt2** [comment]
在1.20.4NeoForge的分支中会改善这一点。
